name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore /home/runner/work/broker-connector-edfi/broker-connector-edfi/src/EdNexusData.Broker.Connector.EdFiAlliance.EdFi.csproj

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="EdNexusData.Broker.Connector.EdFiAlliance.EdFi-$tag-${{ matrix.target }}"

          # Build everything
          dotnet publish /home/runner/work/broker-connector-edfi/broker-connector-edfi/src/EdNexusData.Broker.Connector.EdFiAlliance.EdFi.csproj --framework net8.0 --runtime "${{ matrix.target }}" -c Release -o "$release_name"

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
            tar czvf "${release_name}.tar.gz" "$release_name"
          fi

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "EdNexusData.Broker.Connector.EdFiAlliance.EdFi*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
