name: Publish

run-name: "Publish EdNeuxsData.Broker.Connectors.EdFiAlliance.EdFi"

on:
  push:
    tags:
      - 'edge-*'
  release:
    types: [published]
  repository_dispatch:
    types: [trigger-next]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux/amd64','linux/arm64']
        include:
          - kind: linux/amd64
            os: ubuntu-latest
            target: linux-amd64
          - kind: linux/arm64
            os: ubuntu-latest
            target: linux-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Determine Triggered Tag
        id: triggered_tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "Triggered by Release: ${{ github.event.release.tag_name }}"
            echo "triggered_tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
            echo "TRIGGERED_TAG=${{ github.event.release.tag_name }}" >> "$GITHUB_ENV"
          elif [[ "${{ github.event_name }}" == "repository_dispatch" && "${{ github.event.action }}" == "trigger-next" ]]; then
            echo "Triggered by client-payload: ${{ github.event.client_payload.tag }}"
            echo "triggered_tag=${{ github.event.client_payload.tag }}" >> "$GITHUB_OUTPUT"
            echo "TRIGGERED_TAG=${{ github.event.client_payload.tag }}" >> "$GITHUB_ENV"
          else
            echo "Triggered by Push: ${{ github.ref_name }}"
            echo "triggered_tag=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
            echo "TRIGGERED_TAG=${{ github.ref_name }}" >> "$GITHUB_ENV"
          fi
    
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Authenticate to GitHub Packages
        run: dotnet nuget add source https://nuget.pkg.github.com/ednexusdata/index.json -n github -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore /home/runner/work/broker-connector-edfi/broker-connector-edfi/src/EdNexusData.Broker.Connector.EdFiAlliance.EdFi.csproj

      - name: Build
        shell: bash
        run: |
          tag=${{ env.TRIGGERED_TAG }}
          release_name="EdNexusData.Broker.Connector.EdFiAlliance.EdFi-$tag-${{ matrix.target }}"

          # Build everything
          dotnet publish /home/runner/work/broker-connector-edfi/broker-connector-edfi/src/EdNexusData.Broker.Connector.EdFiAlliance.EdFi.csproj --framework net8.0 --runtime "${{ matrix.target }}" -c Release -o "$release_name"

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
            tar czvf "${release_name}.tar.gz" "$release_name"
          fi

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "EdNexusData.Broker.Connector.EdFiAlliance.EdFi*"
          tag_name: ${{ env.TRIGGERED_TAG }}
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
